---
title: "匆匆又一年"
author: "Byron Chu"
date: "2022-12-22 20:40"
categories: [Life,thoughts]
#image: 
---

1.   小娃

小娃昨日午间回家，抱着我说："我想妈妈了，所以回家。"果然是解铃还须系铃人。

其实，我一直在反省。如果父母能够感受到伤心的话，那么，更为敏感的孩子感受到的伤心失望只会更强烈。这样说来，孩子对我的推拒，也有可能是因为长久的失望。只怕她更伤心吧。

育儿书里推崇温柔地坚持（Gentle Parenting）。原则上看起来有道理，但是操作性堪忧。一个全职工作，还有其它事务缠身的妈妈，维持温柔的能量总是储备不足。

2.  年终总结

2022年伊始，开始重练英语，接受培训和帮助，修改简历，查找工作。四处投简历。其中，终于静脉输注铁。这件事很小，但是对我意义甚大。随后的时间，就是发简历，面试。一轮轮下来。到了三月中才拿到offer。

四月第一周进入新公司，开始工作。一开工即加班无数。几年没有连续无间断地朝九晚五六甚至七，一天下来，心悸不已。

五月，以薄弱的Stata基础转R，对很多东西都不熟悉。一个很简单的工作，都耗时良久。终于将小娃送入Day Care。Day   Care离家很近，私人性质。小娃一周去两天，还是每日哭泣着不要。继续心悸，随后预约医生。六月七月工作带娃照旧，除外多了就医无它。整个夏季的周末都在四处溜娃，几乎逛遍温村公园。

八九月份，开始刷R书籍，刷完第一本，工作流畅度提高斯多。然而，这时候起，或者更早一些，小娃不知为何，睡眠中途总是醒来大哭，发脾气。深夜时分，半睡半醒间，小娃备受压抑的情绪如同火山喷涌而出。没有人是对，没有事情是对。我知平时陪她太少，她其实内心也伤心失望。于是强打精神，细言软语地安慰。大多时候，这一点用都没有。都是她自己完全清醒过来，才肯让好好说话。

这样熬下来，我的睡眠时间也越来越少，越发烦燥。晚上没有睡好的娃，白天反而精神兴奋过度，而且基本失去自我调节与抑制的能力。遇到缺乏睡眠的妈妈，天天家里鸡飞狗跳。妈妈放着声量吼，小娃放开嗓子嚎啕哭。白天不开心的娃，到了该睡的时候也不肯睡，接着捱了批评，只好委屈着睡了。不高兴地睡到半夜，醒来又是一顿大发脾气。完美死循环。

到了九月底某天，晚上只睡了三个多小时，天没亮就去医院。当晚就发烧浑身疼，终于成功被新冠清零了。其实，整个疫情期间，我们没少出门。早先还避着人，尽去户外公园。到了去年年底，有了两针疫苗加持，就存了一较高下的心了。今年五月放开，八月去公司上班，基本就没戴口罩了。这样也没一直感染。我是说，还是因为睡眠太少。

十月开始，全家感染。还连累了爷爷奶奶。小娃烧退之后，精神好了很多，但是持续咳嗽了一个多月。至于我，ZSX一边感染，一边照料小娃，再兼顾工作，第一周精疲力尽，第二三四周还是精力不济。这样就到了小娃生日，简单布置家，开个内部party。之后的日子，小娃随时都想唱生日歌，吹蜡烛。

十一月，飞往美国南部小城---棕榈泉（Palm  Spring）。棕榈泉位于加州，是一处沙漠中的绿洲。一直担心小娃不习惯离家在外，所以在那里只呆了一周。没想到小娃去公园，看飞机，在动物园呆得不想回家。短暂休假之后，继续工作，为各色deadline，继续加班。月末时分，一人在街边，听到悲伤异常的小提琴曲，内心大恸，痛哭了一场。其实并不是因为此小提琴代表着香港的哀鸣。

十二月份，稍有闲暇。有空接着刷第二本R书。同时还有诸多其它事务需要处理，比如参与的一两个项目，准备圣诞，礼物，购物季之类。一晃，又是年底。




