project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: true

website:
  title:  Random Dose of Everything
  page-navigation: true
   
  navbar:
    title: 末 节
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com/byronchu
format:
  html:
    theme: spacelab
    css: styles.css

editor: visual

