---
title: "A  small summary of my week"
description: |
  一周总结
author: Byron Chu
date: 2023-02-26
categories: [Life, Thoughts]
---

### 生活还在继续

周末很快就过去了，我完全没有准备好考试。这两天不知道为什么，特别想刷手机。

其实有些事情，已经盖棺定论了。我不会再这他们身上浪费任何精力与时间。从此，他们与我无关。

但是，关于Shannon，我还是觉得应该送她去Fulltime daycare了。一直以来只是parttime，一来她自己并不愿意，二来，作为一个兰花宝宝，她的性子也很倔犟。但是，目前的感觉是非去不过，一来不用求人来看她。既没有养成良好的习惯，还惹一身躁。二来，生活与学习的习惯都被养坏了，作息，吃饭与英语全面都在拖后脚。而后者让我更介怀。

以后，只能靠自己来， 这样生活与工作都要调整。

1.  早睡早起是必须的。平时留给我自己的时间就会更少了。学习变成了必须挤时间才能完成的事情。

2.  自己也得养成良好的睡眠，休息习惯。尽量全部利用运动减压，可以游泳，zumba或yoga。

3.  周末可以作为movie night陪娃一起看电视节目或者电影。 白天得准备好一周的食物，主要是肉类。这样才能尽量减少每天的cooking时间。

4.  工作的事情要在工作时完成，包括工作相关的学习，以及相关的拓展。

5.  预约acupuncture 和message therapy。自己的身体健康应该放在每一位。

6.  记录生活。并不一定是为了关注或者其它，而这一种与自己的沟通方式。一种清理与沉淀自己的方式。

### AI的棘轮已经启动

ChatGPT引起各国各公司迅速以军事竞赛的方式进入AI领域。以后融合AI，AI辅助的augmented新人类也会开始涌现。其实，如果各个公司找破壁垒，将最优秀的AI产品集成在robot身上，那么离人类的末日也不远了。

对个人来说，使用ChatGPT已经是必选项。学会运用AI，将AI灵活运用在生活工作或者其它的细分领域中，将是最重要的一项工作了。这样一来，对人类既是一种解放，从原有的重复性任务中解放。但是，不可避免的冲击也会到来：被替代。

那么，哪些是暂时不能被替代的？心理学家，很多的医疗服务，基本的水管工之类。作家？真正的创造性的工作，还是需要人类的。

### 考试
考试只有一个月了，而我还是这里写日记。整理自己的思路。以后的时间，要利用做饭的时间去学习，看一两个视频。去上班来回的路上，可以继续背。但是，我直的需要找到时间将这些内容录不来，这样上班的时候就可以一直听。那么每天都得拿出至少一个小时去录下明天要学习的内容。
其实，不是我不想那么做，而是我在录的时候，讲英语的速度远远跟不上，进度非常缓慢。要想办法改进一下。

今天的碎碎念就这样了。






