---
title: "A romanticized history of American Indian"
description: |
  Reviw of Avatar 2: The Way of Water
author: Byron Chu
date: 2022-12-30
categories: [Life,thoughts]
---

##### Concluded 2022 by watching Avatar 2: The Way of Water. I do not regret to watch it. It is a bit lenthy, over 3 hours, but it is not tedious. The plot is full of suspense and tension, on top of the impressive visual effect, which brings to life an abundance of imaginary creatures under water. To be honest, I hesitated to even go to washroom so that I did not miss any scene.

However, in contrast to the intrinsic visual vividness, the weak story line become quite obvious. I do not want to mention how it is basically a replica of the Avatar 1, just from mountain to ocean. I do notice that the core of the story is stemmed from the historical and tragic encounters of American Indian and European colonizers, just overly romanticized.

How come an arrow can pears through the window of the helicopter sent to outer space ? The most intelligent creature, Tabu, in the sea, can tear down human ship using their own rope, meanwhile the brains of its peers s were drilled into and drained for sell on Earth. It is just unrealistic. I understand the reason behind this unrealistics - to appeal for the human conscience. To show people that the beauty, the kind, the innocent, the justice will always win. Kind of balancing out the reality. As we all trained in such a way by society, so we stay kind, innocent, and consider this is the justice in life.

Unfortunately, this romanization only reminds me again and again how the encounters started 400 years ago ended. Brutally. The bows and arrows injured even kills thousand of colonizers. Their strength and skills with spears was invincible at some point, especially when colonizers were just settled and ill-prepared. The rule of thumb is the gun and cannon are faster and efficient in killing massively. The steel boat and helicopters shields off the weapons from stone age. As I read history.

This only leave me wonder, what this movie is trying to convey here does not exist. There is a more fundamental and cruel truth: the survival of the fittest. I know some will call it Social Darwinism. However as far as I can see, the beauty surpass for now, but the most suitable survival to the last.

Last but not the least, by presenting a distorted and sanitized version of events, the over-romanization ignores the reality and sugarcoats the events in history. And people stay comfortable with this distorted reality thus ill-prepared for it, let alone to be trained to deal with this "social Darwinism".

\-\-\-\-\-\-\-\-\--My own version ends here--------------------------------------

The revised version by ChatGPT:

I recently watched Avatar 2: The Way of Water and overall, I really enjoyed it. Although it was a bit long at over 3 hours, the plot kept me engaged with its suspense and tension. The visuals were also impressive, bringing to life all kinds of imaginary creatures under the water. I found myself hesitant to even go to the bathroom during the movie because I didn't want to miss any scenes.

However, the weak storyline became quite obvious in contrast to the stunning visuals. It seemed like a replica of Avatar 1, just set in the ocean instead of the mountains. While the story seemed to be based on the historical and tragic encounters between American Indians and European colonizers, it felt overly romanticized.

I also found some elements of the movie to be unrealistic, such as the idea that an arrow could pierce through the window of a helicopter sent into outer space or that the most intelligent sea creature, Tabu, could tear down a human ship using its own rope. It seemed like these moments were included to appeal to the human conscience and show that beauty, kindness, innocence, and justice always win, but it just felt unrealistic to me.

Furthermore, the romanticization of these encounters reminded me of the brutal reality of how they actually ended. The colonizers were killed by bows and arrows and the indigenous people's strength and skills with spears made them almost invincible at times. However, the colonizers eventually won due to their superior weapons and technology. In my opinion, this movie seems to be trying to convey a message that doesn't align with reality, which is that the survival of the fittest is more fundamental and cruel than the beauty that prevails for now. Some may call this Social Darwinism, but in my view, the most suitable always survive in the end.

By presenting a distorted and sanitized version of historical events, Avatar 2 ignores the reality and sugarcoats the brutality of the encounters between American Indians and European colonizers. This romanticization allows people to remain comfortable with this distorted reality and leaves them ill-prepared to deal with the harsh realities of social Darwinism. Instead of acknowledging the cruel and exploitative nature of these encounters, the movie reinforces harmful ideologies and fails to provide a meaningful way for people to confront and overcome these realities.
